
version: '3.8'

services:
  heidi_zookeeper_dev:
    restart: unless-stopped
    image: "wurstmeister/zookeeper:latest"
    container_name: heidi_zookeeper_dev
#    network_mode: host
    ports:
      - "2181:2181"

  heidi_kafka_dev:
    restart: unless-stopped
    image: "wurstmeister/kafka:latest"
    container_name: heidi_kafka_dev
#    network_mode: host
    depends_on:
      - heidi_zookeeper_dev
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: heidi_zookeeper_dev:2181

      KAFKA_LISTENERS: 'PLAINTEXT://:9092'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

  heidi_mysql_dev:
    restart: unless-stopped
    image: "mysql:8.0.18"
    container_name: heidi_mysql_dev
#    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: abcqwe321
      MYSQL_DATABASE: heidi
      MYSQL_USER: user1
      MYSQL_PASSWORD: abcqwe321
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', "--default-authentication-plugin=mysql_native_password" ]
    ports:
      - "3306:3306"
    volumes:
      - ../init/mysql/:/docker-entrypoint-initdb.d/
    tty: true

#  heidi_profile_dev:
#    restart: unless-stopped
#    image: heidi_task:v1
#    container_name: heidi_profile_dev
#    network_mode: host
#    depends_on:
#      - heidi_zookeeper_dev
#      - heidi_kafka_dev
#      - heidi_mysql_dev
#    links:
#      - heidi_kafka_dev
#    environment:
#      MYSQL_DSN: user1:abcqwe321@tcp(localhost:3306)/heidi?charset=utf8&parseTime=True&loc=Local
#      KAFKA_HOST: localhost:9092
#      KAFKA_GROUP: dev-group
#      KAFKA_TOPIC: dev-topic
#    ports:
#      - "0.0.0.0:10001:10001"
#    command:
#      - sh
#      - -c
#      - |
#        dockerize -wait tcp://localhost:3306 -wait tcp://localhost:9092 -timeout 120s
#        /app/bin/profile
#    tty: true

  heidi_consultation_dev:
    restart: unless-stopped
    image: heidi_task:v1
    network_mode: host
    deploy:
      replicas: 2
    depends_on:
      - heidi_zookeeper_dev
      - heidi_kafka_dev
      - heidi_mysql_dev
#      - heidi_profile_dev
    environment:
      MYSQL_DSN: user1:abcqwe321@tcp(localhost:3306)/heidi
      KAFKA_HOST: localhost:9092
      KAFKA_GROUP: dev-group
      KAFKA_TOPIC: dev-topic
    command:
      - sh
      - -c
      - |
        dockerize -wait tcp://localhost:3306 -wait tcp://localhost:9092 -timeout 120s
        /app/bin/consultation
    tty: true
