
version: '3.9'

services:
  heidi_zookeeper_prod:
    restart: unless-stopped
    image: "wurstmeister/zookeeper:latest"
    container_name: heidi_zookeeper_prod
    ports:
      - "12181:2181"

  heidi_kafka_prod:
    restart: unless-stopped
    image: "wurstmeister/kafka:latest"
    container_name: heidi_kafka_prod
    depends_on:
      - heidi_zookeeper_prod
    ports:
      - "19092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: heidi_zookeeper_prod:2181
      KAFKA_LISTENERS: 'PLAINTEXT://:19092'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

  heidi_mysql_prod:
    restart: unless-stopped
    image: "mysql:8.0.18"
    container_name: heidi_mysql_prod
    environment:
      MYSQL_ROOT_PASSWORD: abcqwe321
      MYSQL_DATABASE: heidi
      MYSQL_USER: user1
      MYSQL_PASSWORD: abcqwe321
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', "--default-authentication-plugin=mysql_native_password" ]
    ports:
      - "3306:3306"
    volumes:
      - ../init/mysql/:/docker-entrypoint-initdb.d/
    tty: true

  heidi_profile_prod:
    restart: unless-stopped
    image: heidi_task:v1
    container_name: heidi_profile_prod
    depends_on:
      - heidi_zookeeper_prod
      - heidi_kafka_prod
      - heidi_mysql_prod
    environment:
      MYSQL_DSN: user1:abcqwe321@tcp(heidi_mysql_prod:13306)/heidi?charset=utf8&parseTime=True&loc=Local
      KAFKA_HOST: heidi_kafka_prod:19092
      KAFKA_GROUP: dev-group
      KAFKA_TOPIC: dev-topic
    ports:
      - "10001:10001"
    command:
      - sh
      - -c
      - |
        dockerize -wait tcp://heidi_mysql_prod:13306 -wait tcp://heidi_kafka_prod:19092 -timeout 120s
        /app/bin/profile
    tty: true

  heidi_consultation_prod:
    restart: unless-stopped
    image: heidi_task:v1
    network_mode: host
    deploy:
      replicas: 2
    depends_on:
      - heidi_zookeeper_prod
      - heidi_kafka_prod
      - heidi_mysql_prod
      - heidi_profile_prod
    environment:
      MYSQL_DSN: user1:abcqwe321@tcp(localhost:13306)/heidi?charset=utf8&parseTime=True&loc=Local
      KAFKA_HOST: localhost:19092
      KAFKA_GROUP: dev-group
      KAFKA_TOPIC: dev-topic
    command:
      - sh
      - -c
      - |
        dockerize -wait tcp://localhost:13306 -wait tcp://localhost:19092 -timeout 120s
        /app/bin/consultation
    tty: true
